version: "3.8"

services:
  db:
    image: postgres:15
    container_name: premier_league_db
    restart: always
    environment:
      POSTGRES_USER: navid
      POSTGRES_PASSWORD: password
      POSTGRES_DB: premier_league_api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  